# Welcome to Jekyll!
# Elliot Hacks - Cybersecurity Blog Configuration

# Site settings
title: "Lets Talk Security - Elliot Hacks"
email: thisguyhack@gmail.com
description: >-
  Welcome to Elliot Hacks! A cybersecurity blog featuring penetration testing tutorials,
  malware analysis, capture the flag writeups, and cutting-edge security research.
  Let's talk security and explore the fascinating world of cybersecurity together!

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author information
author:
  name: "Elliot Jamhuri Nkwama"
  email: "thisguyhack@gmail.com"
  twitter: "elliotH4cks"
  github: "elliot-hacks"
  linkedin: "elliot-hacks"
  location: "Mbeya, Tanzania"

# Social media
social:
  twitter_username: elliotH4cks
  github_username: elliot-hacks
  facebook_username: thisguyhack
  instagram_username: elliot.nkwama
  linkedin_username: elliot-hacks
  medium_username: thisguyhack

# Pagination settings
paginate: 6
paginate_path: "/posts/page:num/"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
---
permalink: /404.html
layout: page
---
